### ISSUE TITLE
[NEW] About load configuration files

### ISSUE THREAD

**Issue by zuozhehao** [ybkuroki/go-webapp-sample#173]
1、Use environment.     
When there are multiple systems running, it is not very convenient

2、Start with parameters
In the development process, if unit testing is needed, especially using Golan, it seems inconvenient to do testing

Whether a third option can be added, using a relative path to load the configuration file .

**Comment by ybkuroki** [comment]
@zuozhehao 
Thank you for your opinion.

How about embed the configuration files to the executable file?
I've implemented the sample in the following branch.
https://github.com/ybkuroki/go-webapp-sample/tree/embed

If we used this method, we don't need to consider where is stored the configuration files.
But, regarding which configurations will we use, we will need to be given to this application using the parameter or the environment variable.
Also, we will need to rebuild this application when we want to update the configuration file.

**Comment by ybkuroki** [comment]
@zuozhehao 
Thank you for your opinion.

> 1、Use environment.
> When there are multiple systems running, it is not very convenient

Please give an environment to the parameter for starting this application if the environment variables are same on the multiple applications.

> 2、Start with parameters
> In the development process, if unit testing is needed, especially using Golan, it seems inconvenient to do testing

Currently, we don't need the parameter for executing the unit tests in this application.
Please refer the followings:
https://github.com/ybkuroki/go-webapp-sample/blob/master/.github/workflows/check.yml#L39

If you do not receive a reply within a month, please let me close this issue.

**Comment by ybkuroki** [comment]
I will close this issue.
Please create a new issue if you have any questions and concerns.
Thanks.
