### ISSUE TITLE
Consider about the features and improvements

### ISSUE THREAD

**Issue by ybkuroki** [ybkuroki/go-webapp-sample#181]
## Purpose
The purpose of this issue is to consider about we will want to add what features and improvement in the future.

## Current remain issues
There is the following remain issues in this repository.
I would like to resolve those issues by discussing with some contributors.

- [Improvement] #173
- [Improvement] #169
- [Improvement] #40

## What we will want to do it
This is some improvements which I considered in the past:

- Implement RBAC (Role Base Access Control)
  - Change from the hardcoding based access control to the RBAC which used the database.
- Implement the authentication using JWT (JSON Web Token)

**Comment by stackkrocket** [comment]
I am interested in discussing further about some the features you would like to implement. I am particularly interested in discussing further on JWT authentication. But also open to helping to contribute to the current open issues.

**Comment by ybkuroki** [comment]
@stackkrocket 
Then, could you please investigate the feasibility of the JWT authentication function?
