### ISSUE TITLE
[Question] GET https://***/api/auth/loginStatus 401 (Unauthorized)

### ISSUE THREAD

**Issue by lghhh** [ybkuroki/go-webapp-sample#204]
## Summary
> GET https://***/api/auth/loginStatus 401 (Unauthorized)

## Cause
> Deploy this to server with nginx proxy_pass

### To reproduce
1. run go-webapp-sample in ubuntu server;
2. use nginx for port forwarding:
![image](https://user-images.githubusercontent.com/23379305/183239240-92fd2a1c-0669-4a66-abc5-492daf9c6eae.png)
3. start vuejs-webapp-sample locally, try to login, then I got
![image](https://user-images.githubusercontent.com/23379305/183239332-e1f02f81-7b46-46e3-b5bb-69e8e8161503.png)
4. logs in server:
![image](https://user-images.githubusercontent.com/23379305/183239293-577d2790-aef3-48c5-9edd-89a1a0824bf7.png)

## Expected behavior
successfully login

## How to deal with this issue
> not solved yet.

**Comment by ybkuroki** [comment]
@lghhh 
Thank you for your report.

I think this cause is that some HTTP headers hasn't been passed by Nginx proxy.
Could you please try the following settings?

https://github.com/ybkuroki/docker-webapp-sample/blob/master/web/vue/server.conf#L15

**Comment by lghhh** [comment]
> @lghhh Thank you for your report.
> 
> I think this cause is that some HTTP headers hasn't been passed by Nginx proxy. Could you please try the following settings?
> 
> https://github.com/ybkuroki/docker-webapp-sample/blob/master/web/vue/server.conf#L15

I try 2 methods, neither works:
1. Set up security groups, open server port mapping, and access go-webapp-sample directly
2. Do as you say
![image](https://user-images.githubusercontent.com/23379305/184049158-0857a5e7-4a0e-4e4c-8aad-4ab3fde9f6c4.png)
I still get 401

**Comment by ybkuroki** [comment]
Thank you for your trying.
Could you please provide a little more information to investigate this cause?

 - What kind of server structure are you trying?
 - Can you run go-webapp-sample without vuejs locally? And in that time, can you logged-in this app?

**Comment by lghhh** [comment]
> Thank you for your trying. Could you please provide a little more information to investigate this cause?
> 
> * What kind of server structure are you trying?
> * Can you run go-webapp-sample without vuejs locally? And in that time, can you logged-in this app?

Thanks for your reply.
1. I use default setting for all, expect repace book table with my own needs.
2. I can run go-webapp-sample without vuejs locally, logged in, create, delete ...
3. Here are some of my settings:

vuejs env:
# environment variables for development

VUE_APP_API_ROOT=https://***.com/

nginx conf:
        location /api/ {
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $http_host;
                proxy_cookie_path / /;
                proxy_pass http://127.0.0.1:8080/api/;
        }

web-app dev yml:
database:
  dialect: sqlite3
  host:  group.db
  port:
  dbname: 
  username: 
  password: 
  migration: true

extension:
  master_generator: true
  cors_enabled: true
  security_enabled: true

log:
  request_log_format: ${remote_ip} ${account_name} ${uri} ${method} ${status}

staticcontents:
  path: ./public/

security:
  auth_path:
    - /api/.*
  exclude_path:
    - /swagger/.*
    - /api/auth/login$
    - /api/auth/logout$
    - /api/health$
  user_path:
    - /api/.*
  admin_path:
    - /api/.*

logs (I added some log for debugging):
![image](https://user-images.githubusercontent.com/23379305/184114755-48ff6a51-c784-4dba-8a45-df93baf1e32c.png)

Thanks for your help!

**Comment by lghhh** [comment]
I succeed with the inner frontend, thanks a lot for your help!

**Comment by ybkuroki** [comment]
Thank you for providing a lot of information and your contacting.
I heard you succeed to start this application and was relieved!

Maybe, I think this is a network issue.
Is the server which vuejs-webapp-sample and go-webapp-sample is running same server?

**Comment by ybkuroki** [comment]
Thank you for providing a lot of information and your contacting.
I heard you succeed to start this application and was relieved!

I will close this issue because this problem was resolved.
Please create a new issue if you have any concerns and any questions.
Thanks.
