### ISSUE TITLE
Error when executing main.go

### ISSUE THREAD

**Issue by rajagopalanrg** [ybkuroki/go-webapp-sample#241]
## Summary
Getting the following error when try to get the source code
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
# github.com/ybkuroki/go-webapp-sample
## Cause
> Why such a problem happened?

### To reproduce
Perform the follwing steps to reproduce the problem.

1. run  go install github.com/ybkuroki/go-webapp-sample@latest

**Comment by ybkuroki** [comment]
@rajagopalanrg 
Thank you for your reporting!

The cause of this issue is that the fix of go-sqlite3 for this warning wasn't reflected because the version of go-sqlite3 wasn't latest. So, I've up to date the version of go-sqlite3, and I've released the new version.

Could you please check whether this issue is resolved or not?

**Comment by rajagopalanrg** [comment]
@ybkuroki I tried to avoid errors with GCC version 9.4.0 but I will try with your up to date code and give my feedback. Thank you for the response.

**Comment by ybkuroki** [comment]
@rajagopalanrg 
Thank you for your reply.
On go-sqlite3 library, it seems that your issue have been already raised in the following ticket. Please check it out if you would like.
`https://github.com/mattn/go-sqlite3/issues/803`

**Comment by rajagopalanrg** [comment]
I deployed PostgreSQL in my locally and changed the config in application.docker.yml but I don't see the DBS created in the PostgreSQL server. Are there some other files to change the connection string?

**Comment by ybkuroki** [comment]
It needs to give the configuration name when you will run this application.

There is 2 ways for running this application by giving the specific configuration.

One is how to give the running parameters like the following:

```bash
$ ./app -env=docker
```

The other is how to give the environment variable like the following:

```bash
$ export WEB_APP_ENV=docker
$ ./app
```

You can also execute this application by using an environment name which you want to give.

1. Create your original configuration: `application.[your favorite name].yml`
1. Execute this application by using the above ways.
