### ISSUE TITLE
Wrong spelling

### ISSUE THREAD

**Issue by rufilboy** [ybkuroki/go-webapp-sample#282]
## Summary
> Write the actual behavior and the purpose to modify.
IN the READ.md file under the **Project map** section, the _following_ is spelt wrongly.

## Cause
> Why such a problem happened?

### To reproduce
Perform the follwing steps to reproduce the problem.

1. …
1. …

## Expected behavior
Expected the follwing behavior.

## How to deal with this issue
> How do you fix it?

**Comment by ybkuroki** [comment]
Thank you for reporting this issue.
I will close this issue because I've fixed the spelling.
