### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by saami97** [ybkuroki/go-webapp-sample#312]
## Summary
> Write the actual behavior and the purpose to modify.

`go test -v . `
 gives out below error:

?       github.com/ybkuroki/go-webapp-sample    [no test files]

### To reproduce
Perform the follwing steps to reproduce the problem.

`go test -v . `

**Comment by ybkuroki** [comment]
@saami97 
I think the reason that you can't execute the test command is there aren't some test files in the root of this project.
Could you please try to the following commands?

1. Move the current directory to the root of this project.
  ```bash
  cd /go-webapp-sample
  ```
1. Perform this test command.
  ```bash
  go test ./... -v
  ```

**Comment by saami97** [comment]
The test ran successfully now.  Thanks for the suggestions!

**Comment by ybkuroki** [comment]
I will close this issue because this issue isn't bug.
