### ISSUE TITLE
[BUG] -- Issue in running the app after a clone

### ISSUE THREAD

**Issue by sanjusjk** [ybkuroki/go-webapp-sample#340]
## Summary
I forked the repo to practice devops(CICD with Jenkins) and from my personal GitHub, I cloned the repo, and I was following the steps mentioned in the readme. However, I have issues with the running of application as it says database connection failure. I couldn't find any information on setting up db in the readme. Also, please note that I already have go installed in my machine along with VS code. I didn't bother to install [MinGW(gcc)](https://sourceforge.net/projects/mingw-w64/files/?source=navbar).

## Cause
> If we need to configure db, that details are not updated, due to which may be this issue.

### To reproduce
Perform the follwing steps to reproduce the problem.

1. In a new machine, follow the steps mentioned in readme and try "go run main.go" (in my case I haven't done this bit "Download and install [MinGW(gcc)](https://sourceforge.net/projects/mingw-w64/files/?source=navbar).")

## Expected behavior
If we follow steps mentioned in readme, we should be able to run the app without any issue

## Screenshot from Terminal
![goapp](https://github.com/ybkuroki/go-webapp-sample/assets/26535858/51769def-64a7-4589-91e1-965b65f97ec5)

**Comment by ybkuroki** [comment]
@sanjusjk 
Thank you for your reporting.
This application is using [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3).
It needs to gcc for building this library. So, I think you wasn't able to access to a database because this library didn't work.
Could you please install gcc following my README?

**Comment by sanjusjk** [comment]
@ybkuroki,

Thank you for responding, I had done this by Installing the gcc and it worked. Thanks!

**Comment by ybkuroki** [comment]
I will close this issue because this issue have resolved.
