### ISSUE TITLE
[NEW] Add a properties file for defining the system messages

### ISSUE THREAD

**Issue by ybkuroki** [ybkuroki/go-webapp-sample#40]
## Purpose
The purpose of this ticket is to be able to manage the messages is returned by the system in the properties file.

## Expected behavior
The expected behavior is the followings:

- Load the properties file when this application have started up.
- This application returns the messages is defined when occurred errors.
- The path of properties file is the root path of this project.

**Comment by dchebakov** [comment]
Could you please provide some examples how the properties file could look like?

**Comment by ybkuroki** [comment]
Sure! Please wait for a moment because I will prepare for the specification.
